### PR TITLE
Add dimensions to Metrics

### PR DESCRIPTION
**Pull request by derjust**
This patchset adds dimensions to the posted metrics in CloudWatch.
This allows to differ between different instances posting the same metrics.

For ease of deployment, EC2 metadata templates are supported from `com.amazonaws.util.EC2MetadataUtils`:

```
{
   "obj":"net.sf.ehcache:type=CacheStatistics,CacheManager=__DEFAULT__,name=MyCache",
   "attr":[
      "CacheHits",
      "CacheMisses",
      "ObjectCount"
   ],
   "resultAlias":"EHCache",
   "outputWriters":[
      {
         "@class":"com.googlecode.jmxtrans.model.output.CloudWatchWriter",
         "settings":{
            "namespace":"jmxtrans",
            "dimensions":[
               {
                  "name":"Cache",
                  "value":"MyCache"
               },
               {
                  "name":"InstanceId",
                  "value":"$InstanceId"
               }
            ]
         }
      }
   ]
}
```

Supported EC2 meta values are:

 * $PublicKey
 * $AmiId
 * $AmiLaunchIndex
 * $AmiManifestPath
 * $AncestorAmiIds
 * $InstanceAction
 * $InstanceId
 * $InstanceType
 * $LocalHostName
 * $MacAddress
 * $PrivateIpAddress
 * $AvailabilityZone
 * $ProductCodes
 * $RamdiskId
 * $ReservationId
 * $SecurityGroups
 * $IAMInstanceProfileInfo
 * $InstanceInfo
 * $EC2InstanceRegion
 * $IAMSecurityCredentials
 * $BlockDeviceMapping
 * $NetworkInterfaces
 * $UserData
 * $Items
 * $Data
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/jmxtrans/jmxtrans/pull/373%23issuecomment-164880145%22%2C%20%22https%3A//github.com/jmxtrans/jmxtrans/pull/373%23issuecomment-164929094%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/jmxtrans/jmxtrans/pull/373%23issuecomment-164880145%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22I%20tried%20to%20do%20some%20cleanup%20to%20the%20CloudWatchWriter%20%28https%3A//github.com/jmxtrans/jmxtrans/tree/derjust%29%20including%20your%20changes.%20It%20still%20needs%20some%20more%20tests%2C%20but%20should%20be%20OK%20to%20merge%20soon.%20Could%20you%20already%20have%20a%20look%20and%20see%20if%20it%20looks%20good%20to%20you%3F%22%2C%20%22created_at%22%3A%20%222015-12-15T20%3A04%3A23Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1415765%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/gehel%22%7D%7D%2C%20%7B%22body%22%3A%20%22Looks%20good%20to%20me%20%3A%2B1%3A%20%22%2C%20%22created_at%22%3A%20%222015-12-15T23%3A04%3A53Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/2053353%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/derjust%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [x] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/jmxtrans/jmxtrans/pull/373#issuecomment-164880145'>General Comment</a></b>
- <a href='https://github.com/gehel'></a> I tried to do some cleanup to the CloudWatchWriter (https://github.com/jmxtrans/jmxtrans/tree/derjust) including your changes. It still needs some more tests, but should be OK to merge soon. Could you already have a look and see if it looks good to you?
- <a href='https://github.com/derjust'></a> Looks good to me :+1:

<a href='https://www.codereviewhub.com/jmxtrans/jmxtrans/pull/373?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/jmxtrans/jmxtrans/pull/373?approve=1'></a>&nbsp;<a href='https://github.com/jmxtrans/jmxtrans/pull/373'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by gehel** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/jmxtrans/jmxtrans/pull/373'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by gehel** [comment]
I tried to do some cleanup to the CloudWatchWriter (https://github.com/jmxtrans/jmxtrans/tree/derjust) including your changes. It still needs some more tests, but should be OK to merge soon. Could you already have a look and see if it looks good to you?

**Comment by derjust** [comment]
Looks good to me :+1:

**Comment by gehel** [comment]
Replaced by #378.

**Pull request closed without merging**
