### PR TITLE
Modularisation

### PR DESCRIPTION
**Pull request by gehel**
All code is split in multiple modules. The split choosen for the different modules is always a matter of taste, but here is my take:

* core of JmxTrans
* utilities
* output writers
  ** with submodules for each family of output writer
* packaging

All unit tests are passing, basic tests with RPM and DEB packages indicate that they are working.

I expect that more work is required to have reporting in Maven site working smoothly, but this should be done in a second time.

This is a BIG pull request. I'd love to have other eyes on it (at least testing the RPM / DEB) before merging. @bijugs: as you seem to be a knowledgeable user of the RPM, I would welcome your feedback very much !
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/jmxtrans/jmxtrans/pull/290%23issuecomment-100696517%22%2C%20%22https%3A//github.com/jmxtrans/jmxtrans/pull/290%23issuecomment-100696603%22%2C%20%22https%3A//github.com/jmxtrans/jmxtrans/pull/290%23issuecomment-100696792%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/jmxtrans/jmxtrans/pull/290%23issuecomment-100696517%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3A%2B1%3A%20%5Cr%5Cn%5Cr%5CnMaybe%20also%20rename%20the%20package%20to%20org.jmxtrans%3F%22%2C%20%22created_at%22%3A%20%222015-05-10T20%3A22%3A53Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/85355%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/lookfirst%22%7D%7D%2C%20%7B%22body%22%3A%20%22Not%20sure%20about%20renaming%20the%20package.%20The%20conf%20files%20reference%20the%20OutputWriters%20by%20qualified%20name%2C%20so%20this%20would%20make%20a%20non%20backward%20compatible%20change.%22%2C%20%22created_at%22%3A%20%222015-05-10T20%3A24%3A28Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1415765%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/gehel%22%7D%7D%2C%20%7B%22body%22%3A%20%22Oh%20right...%20we%20could%20always%20hack%20jackson%20to%20rename%20it%20before%20instantiating%20it...%22%2C%20%22created_at%22%3A%20%222015-05-10T20%3A27%3A44Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/85355%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/lookfirst%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/jmxtrans/jmxtrans/pull/290#issuecomment-100696517'>General Comment</a></b>
- <a href='https://github.com/lookfirst'></a> :+1:
Maybe also rename the package to org.jmxtrans?
- <a href='https://github.com/gehel'></a> Not sure about renaming the package. The conf files reference the OutputWriters by qualified name, so this would make a non backward compatible change.
- <a href='https://github.com/lookfirst'></a> Oh right... we could always hack jackson to rename it before instantiating it...

<a href='https://www.codereviewhub.com/jmxtrans/jmxtrans/pull/290?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/jmxtrans/jmxtrans/pull/290?approve=1'></a>&nbsp;<a href='https://github.com/jmxtrans/jmxtrans/pull/290'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by gehel** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/jmxtrans/jmxtrans/pull/290'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by lookfirst** [comment]
:+1: 

Maybe also rename the package to org.jmxtrans?

**Comment by gehel** [comment]
Not sure about renaming the package. The conf files reference the OutputWriters by qualified name, so this would make a non backward compatible change.

**Comment by lookfirst** [comment]
Oh right... we could always hack jackson to rename it before instantiating it...

**Comment by gehel** [comment]
Merging this already. We can still discuss package renaming and do it in another PR.

**Pull request merged**
