### PR TITLE
Remove empty type names

### PR DESCRIPTION
**Pull request by conorbev**
Cleaner way to fix the issue I'm seeing with Yammer metrics when they include empty typeNames as was discussed in https://github.com/jmxtrans/jmxtrans/pull/271
<a href='#crh-start'></a><a href='#crh-data-%7B%22approved%22%3A%20%7B%22https%3A//github.com/lookfirst%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/85355%3Fv%3D3%22%7D%7D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/jmxtrans/jmxtrans/pull/277%23issuecomment-94896183%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222015-04-21T18%3A26%3A33Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/85355%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/lookfirst%22%7D%7D%2C%20%7B%22body%22%3A%20%22Looks%20good%20to%20me.%20Waiting%20for%20Travis%20to%20finish%20its%20job%20before%20merging%2C%20just%20on%20principle%20...%22%2C%20%22created_at%22%3A%20%222015-04-21T18%3A36%3A50Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1415765%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/gehel%22%7D%7D%2C%20%7B%22body%22%3A%20%22Yes%2C%20agreed...%20if%20I%20approve%20a%20PR%2C%20it%20is%20definitely%20conditional%20on%20travis%20first%20as%20well.%20%3D%29%22%2C%20%22created_at%22%3A%20%222015-04-21T18%3A52%3A18Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/85355%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/lookfirst%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22processed%22%3A%20%5B%22https%3A//github.com/jmxtrans/jmxtrans/pull/277%23issuecomment-94896183%22%2C%20%22https%3A//github.com/jmxtrans/jmxtrans/pull/277%23issuecomment-94899078%22%2C%20%22https%3A//github.com/jmxtrans/jmxtrans/pull/277%23issuecomment-94903452%22%5D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>

<a href='https://github.com/lookfirst'></a>

- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/jmxtrans/jmxtrans/pull/277#issuecomment-94896183'>General Comment</a></b>
- <a href='https://github.com/lookfirst'></a> :shipit:
- <a href='https://github.com/gehel'></a> Looks good to me. Waiting for Travis to finish its job before merging, just on principle ...
- <a href='https://github.com/lookfirst'></a> Yes, agreed... if I approve a PR, it is definitely conditional on travis first as well. =)

<a href='https://www.codereviewhub.com/jmxtrans/jmxtrans/pull/277?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/jmxtrans/jmxtrans/pull/277?approve=1'></a>&nbsp;<a href='https://www.codereviewhub.com/jmxtrans/jmxtrans/pull/277?approve=0'></a>&nbsp;<a href='https://github.com/jmxtrans/jmxtrans/pull/277'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by gehel** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/jmxtrans/jmxtrans/pull/277'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by lookfirst** [comment]
:shipit:

**Comment by gehel** [comment]
Looks good to me. Waiting for Travis to finish its job before merging, just on principle ...

**Comment by lookfirst** [comment]
Yes, agreed... if I approve a PR, it is definitely conditional on travis first as well. =)

**Comment by gehel** [comment]
I need to spend some time optimizing the build. 29 minutes is ridiculous. I love PIT, but at that price it is getting a bit too expensive ...

**Comment by conorbev** [comment]
The travis build could have different characteristics but when I build locally the thing that takes the most time by far is CloudWatchWriterTests.testValidationWithoutSettings I think it waits for some kind of timeout or something.

**Pull request merged**
