### PR TITLE
AppVeyor Step 2

### PR DESCRIPTION
**Pull request by gquintana**

### CODE REVIEW

**Comment by gquintana** [comment]
I think the CI Job should be created using the jmxtrans account to avoid having my name in URLs: https://ci.appveyor.com/project/gquintana/jmxtrans

**Comment by gquintana** [comment]
As you can see in PR Checks, I added an AppVeyor check \o/

**Comment by gehel** [comment]
I don't think we have a jmxtrans account on AppVeyor yet. I just registered to AppVeyor, I don't see an obvious way to map our jmxtrans github organization to AppVeyor. Feel free to go ahead and do whatever needs doing... and share credentials with the rest of the jmxtrans team if you need to create any new creds...

**Comment by gquintana** [comment]
@gehel  It's a pure assumption: project *Owners* may be able to log into AppVeyor using *jmxtrans* Github user. I'm only *Member*.

**Comment by gehel** [comment]
There is no jmxtrans github user, there is a jmxtrans github organization. If I try to create a jmxtrans project in AppVeyor, it appears under my username (gehel). So let's build it under your name atm. It does not matter much...

**Pull request merged**
