### PR TITLE
Now correctly ensure only one instance of an output writer is created.

### LINKED ISSUE #453: JMXTrans Creating Duplicate OutputWriters
As of 254, JMXTrans is creating duplicate outputwriters during initialization, only one of which is used.  This leads to unnecessary resource consumption.   #441 has more details

### PR DESCRIPTION
**Pull request by gehel**
This is ugly, it does require more cleanup , but it should work.

Should fix #453 and improve #441
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/jmxtrans/jmxtrans/pull/456%23issuecomment-216590894%22%2C%20%22https%3A//github.com/jmxtrans/jmxtrans/pull/456%23issuecomment-216591894%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/jmxtrans/jmxtrans/pull/456%23issuecomment-216590894%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22It%20looks%20good%20from%20the%20perspective%20of%20not%20creating%20more%20than%20one%20%60OutputWriterFactory%60.%5Cr%5Cn%5Cr%5CnThere%20will%20still%20be%20problems%20when%20using%20an%20old%20style%20%60OutputWriter%60%20right%3F%22%2C%20%22created_at%22%3A%20%222016-05-03T16%3A44%3A36Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6921953%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/kevinconaway%22%7D%7D%2C%20%7B%22body%22%3A%20%22It%20%2Ashould%2A%20not%20create%20more%20than%20one%20%60OutputWriterFactory%60%20and%20not%20instantiate%20more%20than%20once%20an%20%60OutputWriter%60.%20The%20problem%20mostly%20still%20exist%20with%20the%20old%20%60OutputWriter%60s%2C%20but%20they%20are%20much%20more%20lightweight%20than%20the%20new%20ones%2C%20so%20having%20multiple%20instance%20was%20never%20an%20issue%20with%20them%20%28unless%20I%20broke%20even%20more%20stuff%20than%20I%20thought...%29.%22%2C%20%22created_at%22%3A%20%222016-05-03T16%3A47%3A03Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1415765%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/gehel%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/jmxtrans/jmxtrans/pull/456#issuecomment-216590894'>General Comment</a></b>
- <a href='https://github.com/kevinconaway'></a> It looks good from the perspective of not creating more than one `OutputWriterFactory`.
There will still be problems when using an old style `OutputWriter` right?
- <a href='https://github.com/gehel'></a> It *should* not create more than one `OutputWriterFactory` and not instantiate more than once an `OutputWriter`. The problem mostly still exist with the old `OutputWriter`s, but they are much more lightweight than the new ones, so having multiple instance was never an issue with them (unless I broke even more stuff than I thought...).

<a href='https://www.codereviewhub.com/jmxtrans/jmxtrans/pull/456?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/jmxtrans/jmxtrans/pull/456?approve=1'></a>&nbsp;<a href='https://github.com/jmxtrans/jmxtrans/pull/456'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by gehel** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/jmxtrans/jmxtrans/pull/456'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by kevinconaway** [comment]
It looks good from the perspective of not creating more than one `OutputWriterFactory`.

There will still be problems when using an old style `OutputWriter` right?

**Comment by gehel** [comment]
It *should* not create more than one `OutputWriterFactory` and not instantiate more than once an `OutputWriter`. The problem mostly still exist with the old `OutputWriter`s, but they are much more lightweight than the new ones, so having multiple instance was never an issue with them (unless I broke even more stuff than I thought...).

**Comment by gehel** [comment]
Ok, merging this, let's do some more testing on the next SNAPSHOT...

**Comment by kevinconaway** [comment]
Sounds good.

**Pull request merged**
