### PR TITLE
Don't create jmxtrans user if it exist already

### PR DESCRIPTION
**Pull request by hgomez**
https://github.com/jmxtrans/jmxtrans/issues/281
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/jmxtrans/jmxtrans/pull/285%23issuecomment-95857089%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/jmxtrans/jmxtrans/pull/285%23issuecomment-95857089%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22I%20think%20that%20%60rpm/SPECS/jmxtrans.spec%60%20isn%27t%20used%20at%20all%20anymore.%20We%20should%20probably%20remove%20it%20at%20some%20point%20to%20reduce%20confusion.%20In%20the%20meantime%2C%20aligning%20the%20content%20is%20a%20very%20good%20thing%20%21%22%2C%20%22created_at%22%3A%20%222015-04-24T08%3A51%3A13Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1415765%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/gehel%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/jmxtrans/jmxtrans/pull/285#issuecomment-95857089'>General Comment</a></b>
- <a href='https://github.com/gehel'></a> I think that `rpm/SPECS/jmxtrans.spec` isn't used at all anymore. We should probably remove it at some point to reduce confusion. In the meantime, aligning the content is a very good thing !

<a href='https://www.codereviewhub.com/jmxtrans/jmxtrans/pull/285?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/jmxtrans/jmxtrans/pull/285?approve=1'></a>&nbsp;<a href='https://github.com/jmxtrans/jmxtrans/pull/285'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by gehel** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/jmxtrans/jmxtrans/pull/285'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by gehel** [comment]
I think that `rpm/SPECS/jmxtrans.spec` isn't used at all anymore. We should probably remove it at some point to reduce confusion. In the meantime, aligning the content is a very good thing !

**Comment by gehel** [comment]
Thanks a lot for the help !

**Comment by hgomez** [comment]
If you don't use rpm dir contents anymore, yes better remove it to avoid confusion

**Pull request merged**
