### PR TITLE
Refactoring scheduler

### PR DESCRIPTION
**Pull request by gehel**
This is a major cleanup that tries to have a simpler implementation of query execution, scheduling and reporting. This touches the core of JmxTrans.

I'd love to get some feedback, test, experimentations, ... on this branch.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/jmxtrans/jmxtrans/pull/380%23issuecomment-166435013%22%2C%20%22https%3A//github.com/jmxtrans/jmxtrans/pull/380%23issuecomment-166436267%22%2C%20%22https%3A//github.com/jmxtrans/jmxtrans/pull/380%23issuecomment-166442673%22%2C%20%22https%3A//github.com/jmxtrans/jmxtrans/pull/380%23issuecomment-166817055%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/jmxtrans/jmxtrans/pull/380%23issuecomment-166435013%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22So%20glad%20you%27re%20in%20charge.%20%3D%29%20Seriously.%22%2C%20%22created_at%22%3A%20%222015-12-21T21%3A57%3A01Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/85355%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/lookfirst%22%7D%7D%2C%20%7B%22body%22%3A%20%22I%27m%20just%20having%20fun%21%20And%20I%20still%20owe%20you%20a%20few%20beers.%20Any%20chance%20you%27d%20be%20in%20San%20Francisco%20in%20January%3F%22%2C%20%22created_at%22%3A%20%222015-12-21T22%3A03%3A09Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1415765%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/gehel%22%7D%7D%2C%20%7B%22body%22%3A%20%22I%27m%20gone%20end%20of%20Jan%20and%20on%20a%20few%20weekends%2C%20but%20I%27ll%20be%20around%20for%20the%20rest%20of%20it.%20I%20think%20I%20owe%20you%20the%20beers%20though.%20%3D%29%22%2C%20%22created_at%22%3A%20%222015-12-21T22%3A34%3A24Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/85355%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/lookfirst%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3A%2B1%3A%22%2C%20%22created_at%22%3A%20%222015-12-23T07%3A04%3A05Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1415765%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/gehel%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [x] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/jmxtrans/jmxtrans/pull/380#issuecomment-166435013'>General Comment</a></b>
- <a href='https://github.com/lookfirst'></a> So glad you're in charge. =) Seriously.
- <a href='https://github.com/gehel'></a> I'm just having fun! And I still owe you a few beers. Any chance you'd be in San Francisco in January?
- <a href='https://github.com/lookfirst'></a> I'm gone end of Jan and on a few weekends, but I'll be around for the rest of it. I think I owe you the beers though. =)

<a href='https://www.codereviewhub.com/jmxtrans/jmxtrans/pull/380?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/jmxtrans/jmxtrans/pull/380?approve=1'></a>&nbsp;<a href='https://github.com/jmxtrans/jmxtrans/pull/380'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by gehel** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/jmxtrans/jmxtrans/pull/380'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by lookfirst** [comment]
So glad you're in charge. =) Seriously.

**Comment by gehel** [comment]
I'm just having fun! And I still owe you a few beers. Any chance you'd be in San Francisco in January?

**Comment by lookfirst** [comment]
I'm gone end of Jan and on a few weekends, but I'll be around for the rest of it. I think I owe you the beers though. =)

**Comment by gehel** [comment]
:+1:

**Pull request merged**
