### PR TITLE
Fix broken logging 

### PR DESCRIPTION
**Pull request by praste**
This fixes issue #221 . 
We have both log4j and logback jars and looks like slf4j is hitting logback jar first(as classloader seems to be loading those before log4j). In this case logback ignore log4j.xml and uses default configuration where it spits out everything to console. Default console logger is synchronous and hence it could be performance issue as well if we are logging too much.

Logback has really cool features like ability to change log level at runtime using JMX (which is available in log4j2 but not in log4j)

I have put together logback.xml to mimic intending log configuration we were trying to achieve using log4j.xml, with some more added features like automatically delete log file more than 15 days old.

### CODE REVIEW

**Comment by gehel** [comment]
This is a rework of #223. As I said there, this strictly breaks compatibility by changing log4j.xml to logback.xml.

I think it still make sense to merge this as if fixes the long standing issue of logging being broken in JmxTrans. That being said, with my too fast merge on the first PR, I'm going to wait for @lookfirst opinion this time ;-)

**Comment by lookfirst** [comment]
:+1:

**Comment by praste** [comment]
I am not sure why my fix is not showing up in the master branch. I still
see a log4j.xml file in 'src' folder and no 'logback.xml there.

**Comment by gehel** [comment]
Most probably my fault ... It was late yesterday, my rewrite was probably faulty. Apologies... Any chance you could resend another PR ?

**Comment by praste** [comment]
Looks like I shot my self in the foot as well, now pull request says,
'there isn't anything to compare'

**Comment by gehel** [comment]
I love git, except when I'm tired ...

**Comment by praste** [comment]
where did logback go. I just pulled latest code and don't see logback.xml. 

Looks like someone inadvertently changed logging back you use log4j ?

**Comment by gehel** [comment]
That's probably a mistake. In anycase, logging is mostly broken. We really need to remove all direct dependencies to log4j and logback (see #215). But this will probably require breaking backward compatibility.

Feel free to send a PR to add logback.xml again if you can tet that it works correctly. Integration test is of course more than welcomed!

**Pull request merged**
