### PR TITLE
Fix: ObjectAlreadyExistsException because one already exists

### PR DESCRIPTION
**Pull request by yyvess**
Triggers name are  generated with currentTimeMillis() and in some case two triggers can have same generated name.

That cause the following error on the service loading :

> ERROR (com.googlecode.jmxtrans.JmxTransformer:190) - Error scheduling job for server: 
> Caused by: org.quartz.ObjectAlreadyExistsException: Unable to store Trigger with name: 'test.nespresso.com:9200-1490623007618' and group: 'DEFAULT', because one already exists with this identification.

I have replace  currentTimeMillis() by nanoTime() to fix this issue.

### CODE REVIEW

**Comment by gehel** [comment]
Thanks for the fix! Longer term, we need to get rid of quartz, a simple ScheduledExecutorService would be much simpler...

**Comment by gehel** [comment]
@yyvess let me know if you need a new release with that fix...

**Comment by blaiseb** [comment]
Thanks for the merge @gehel ! I was the one who asked @yyvess for this fix. If you can do a new release we would greatly appreciate

**Comment by gehel** [comment]
Minor issue with the build and PGP keys that needs to be fixed, but I'll release ASAP...

**Comment by gehel** [comment]
Ok, PGP key was expired, this should now work better...

**Comment by gehel** [comment]
release is done, should be available on maven central soon...

**Comment by yyvess** [comment]
Thanks !!

**Pull request merged**
